### ISSUE TITLE
Slideshow for front page or randomly selected image.

### ISSUE THREAD

**Issue by webmasterkai** [bjornmeansbear/MFAthesis2014#1]

**Comment by emmasf** [comment]
Randomly selected image, please. If we want to curate the options, is the best way to create another folder in the main dropbox folder with images we want?

**Comment by webmasterkai** [comment]
That seems logical. I think I'll need to have one of the dropbox accounts authenticate so the app has access to all the images. What will the name of the folder be? "slideshow"?

**Comment by emmasf** [comment]
I pulled them into github: img/headers
They're huge files. Ultimately we may make them taller. But we can start here.

**Comment by bjornmeansbear** [comment]
Tim finished this
