### ISSUE TITLE
firstname and lastname are not always available.

### ISSUE THREAD

**Issue by tlupfer** [bjornmeansbear/MFAthesis2014#11]
Click on http://localhost:8000/#id=540707 (or whatever your local development host is) and click around the students. The many "bryan hempels" are actually other students that have a "name" field, but not firstname and lastname. Should we just use name instead?

**Comment by bjornmeansbear** [comment]
In the google doc itself there appear to be no names missing; there must be some issue when parsing it for the site... @kai will have to help look at this.

**Comment by bjornmeansbear** [comment]
Seems to be a problem with just the MA teaching and Critical Studies groups... It could be that these students have IDs and dates associated with them from some other document, but don't have major entries in the main Student Response google doc... having @nourtabet investigate

**Comment by bjornmeansbear** [comment]
Okay, if people don't have names (which means they will most likely be missing almost all fields of information) is there a way to just "hide" their entries from showing? that'll be the best solution — if this can be solved in tandem with https://github.com/bjornmeansbear/MFAthesis2014/issues/17

**Comment by bjornmeansbear** [comment]
The answer is as follows: Critical studies students just don't have data entries, they are simply to be omitted from the lower student area all together. MA Teaching people may not have yet entered their data, so when they do, their names should show up!
