### ISSUE TITLE
Can an Icon be used for website and email?

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#15]
These are sometimes really long fields, and don't break well... Can we icon them up instead ?
@nourtabet @emmasf just curious about your thoughts on the single student overlay application

**Comment by emmasf** [comment]
Hells yeah

Typed on a phone, please excuse brevity.

**Comment by bjornmeansbear** [comment]
Great. I'll put in the github glyphicons for now, and then you two can then decide if they will suffice or if we need to design up something... I'll do it once done with my class tonight.

**Comment by bjornmeansbear** [comment]
This is so.
