### ISSUE TITLE
I horribly broke overlay functionality on < 768 screens somehow

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#16]
Can you give me some help @tlupfer ?

**Comment by tlupfer** [comment]
What are we looking for here? A different template or just getting the buttons working again? We could do the same thing we did with R&G and use different templates if that's easier.

**Comment by bjornmeansbear** [comment]
So, there isn't a problem with the template. It is something to do with me adding a new nav only for mobile views. This just shows/hides with the hidden/visible helper classes from bootstrap. Once I commited all that menu/nav stuff, then the overlay disapears in <768 screen mode — for example, open up a student project in normal screen width and then collapse the width down, the overlay suddenly dissapears. I can't figure out where/what I messed with to make this happen

**Comment by bjornmeansbear** [comment]
Feck. Nevermind, it seems to be working fine now. I can't make it not work... Nice work @tlupfer :)
