### ISSUE TITLE
Come up with way to easily disable student entries

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#17]
There are a few people who don't have images, etc. and don't want to be on the site for launch, but might want to be turned back on/added back later ... what's the easiest way to deal with this without just deleting them from the google doc?

**Comment by nourtabet** [comment]
People to delete from the website:
Steve Sachs // Pbacc FA // id0475068
Elizabeth Reid // Pbacc FA // id0536518

**Comment by webmasterkai** [comment]
Add a column or something. call it 'disable' or something. then just put an x in the row of the folks you want removed.

**Comment by emmasf** [comment]
Okay, my bit's done. There's now a column 0 called "disable;" students that should be hidden (including the two above) have an x in this column.

**Comment by emmasf** [comment]
Column O, that is.

**Comment by bjornmeansbear** [comment]
@webmasterkai Emma has added the column you asked for. Let us know if you need anything else to make this work.

**Comment by bjornmeansbear** [comment]
I have lists of student IDs that should not be shown until later in May when a second wave of students entries will be captured and/or updated. Is this more useful than the disable column — only some of these people are currently in the student data spreadsheet is this confusing? …

MAT
443278
437771
443564
459986
440087
445165
464062
464187
453166
448744
453220
401805
415768
524679
443123
420845
361711

MAAE 
524263
109518
524174
510825
354221
538833
542280
542281
155088
541960

MFAST 
333264
500817
317278
498556
481509
499451
480908
463878

**Comment by bjornmeansbear** [comment]
These students should be hidden as well:

Critical Studies:
499514
515940
540707
538221
530304
535795

**Comment by bjornmeansbear** [comment]
And these two:

536518
475068

@webmasterkai is there a better place/format for me to make this list for you?

**Comment by bjornmeansbear** [comment]
@webmasterkai hopefully this will work: https://github.com/bjornmeansbear/MFAthesis2014/blob/master/hiddenstudents.txt

**Comment by tlupfer** [comment]
For now, I also added a js solution that can be removed after the import is working correctly. To add ids, there is an array on line 6 of the js file. Add any ids that shouldn't appear here.

**Comment by bjornmeansbear** [comment]
@webmasterkai has this been "solved" should I close this, or do we still need to work out a longterm fix as more students will be being added or potentially subtracted?

**Comment by webmasterkai** [comment]
There is a list of ID's that will not be pulled from the galleries sheet. The entries in the student responses will not pull if they have an x. Line 161 https://github.com/sundaysenergy/make.cape.io/blob/master/make_files/mfa.yaml

Closes #17
