### ISSUE TITLE
missing info: AARON RICHMOND id 341932

### ISSUE THREAD

**Issue by nourtabet** [bjornmeansbear/MFAthesis2014#20]
his info is missing although it's in the spreadsheet
https://docs.google.com/a/mica.edu/spreadsheet/ccc?key=0Al-kEdVYvxtGdG1wOEFNUUNEWW1CaDBlbXBHYlhQN0E&usp=drive_web#gid=0

**Comment by bjornmeansbear** [comment]
I think somehow his info was getting split into 2 data objects, Nour made sure that the spreadsheet info had the correct ID, Name, Etc. to hopefully resolve this.

**Comment by webmasterkai** [comment]
I can reimport the data

**Comment by bjornmeansbear** [comment]
Yes, and I think there might be some more DropBox images. I can get specifically who was added if that makes importing easier?

**Comment by bjornmeansbear** [comment]
Kai pulled new spreadsheet data Aaron appears to display correctly now.
