### ISSUE TITLE
When/How can we pull new changes from DB and/or spreadsheet?

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#21]
Semi-related to #20

**Comment by bjornmeansbear** [comment]
There will be more updates being made to the student data spreadsheet for sure as a couple more programs will be entering data in the coming weeks that have later thesis presentations.

**Comment by webmasterkai** [comment]
Just tell me how often you want it to get updates.

**Comment by bjornmeansbear** [comment]
I'll figure this out with the MICA team and come up with an answer I guess... The only other thing would be how this pushes the compiled results to the MICA server for archiving... although, it seems to work okay from my local machine just grabbing down the images and JSON from the cape.io server. This could be the solution for now as well and the JSON then just gets updated every once in a while?

**Comment by bjornmeansbear** [comment]
related to #49
