### ISSUE TITLE
There are some poorly aliased images — our fault, or the original images fault?

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#22]

**Comment by bjornmeansbear** [comment]
For sure check Nour Tabet's

**Comment by bjornmeansbear** [comment]
Also check Ricki Blake's

**Comment by emmasf** [comment]
They look nice now. Perhaps you all did something or perhaps it was magic.

**Comment by bjornmeansbear** [comment]
I think the images got pulled in again perhaps...

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear
