### ISSUE TITLE
Make program names and dates in Schedule section link to correct Student filters

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#24]
Scroll down the page and filter the student results please.

**Comment by tlupfer** [comment]
This is now implemented on the gallery text. I'm going to wait until the opening date thing gets figured out to implement it on the schedule.

**Comment by bjornmeansbear** [comment]
I think the galleries section works grand. According to #33 it appears that @emmasf updated the schedule with correct dates/times, so perhaps thats ready to get done then too.

**Comment by tlupfer** [comment]
This one is now done with the schedule dates as well

**Comment by bjornmeansbear** [comment]
Thanks @tlupfer
