### ISSUE TITLE
Filters and search terms to appear somewhere...

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#25]
At the very least they need to be highlighted in the menu; maybe they can print out after/under "Students" in the main column?

**Comment by tlupfer** [comment]
yeah, I think the latter makes sense. I can do that.

**Comment by bjornmeansbear** [comment]
@tlupfer this isn't too big a deal?

**Comment by bjornmeansbear** [comment]
@emmasf This will get done for you :)

**Comment by emmasf** [comment]
Fantastic! Win for usability. People were confused.

Do you guys want a design for where to print out the filter? Or, I can style it once you've created whatever bit is needed (mustache object? educate me.).

Thanks!

**Comment by tlupfer** [comment]
This one should be in place. There's a div with the id active-filter and a close button inside of it. Close button clears the existing filter

**Comment by bjornmeansbear** [comment]
I dig this solution. I'll style it later today, unless @emmasf or @nourtabet want to jump on that.

**Comment by emmasf** [comment]
Awesome, thank you! Kristian, I'm happy to style it unless you have already.
