### ISSUE TITLE
Make slideshow display dynamic

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#28]
If there are no images, print out none of the SS stuff at all
If only 1 image, just print out an image, and still none of the SS stuff.

**Comment by tlupfer** [comment]
Latest commit has both of these features. mfa.cape.io doesn't seem to be updating.

**Comment by bjornmeansbear** [comment]
Great. Thank you. Yeah, kai was on the updating issue, but its not clear what is happening.
