### ISSUE TITLE
It's about 34 times easier if we move AboutShow to a github md file.

### ISSUE THREAD

**Issue by webmasterkai** [bjornmeansbear/MFAthesis2014#3]
https://docs.google.com/a/sundaysenergy.com/document/d/181k7UtYfjSsumP4QQpTsjkRaun3wWPRWMQvleEg8KiM/edit

Can that just be a markdown file here in this repo?

**Comment by webmasterkai** [comment]
See https://github.com/bjornmeansbear/MFAthesis2014/commit/2529ded225c233289793201a871a06ed4c5a0a6c

**Comment by emmasf** [comment]
Great idea. Let's do it. Please feel free to suggest improvements to the structure, I just made something up.

Typed on a phone, please excuse brevity.

**Comment by bjornmeansbear** [comment]
this is so.
https://github.com/bjornmeansbear/MFAthesis2014/blob/master/content/aboutshow.md
