### ISSUE TITLE
What to do about the captions...???

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#30]
A) they are mostly not plain text
B) they are in so many different formats

If they are just plain text, then does that solve this problem and make it easy?

**Comment by webmasterkai** [comment]
Some people took a screen shot of the text file and uploaded that. A yaml is easiest for me.

**Comment by bjornmeansbear** [comment]
what then is the best structure, just using the image number — 01, 02, 03 — as the "object" and then each piece of info as a sub-declaration?

like this:

  01
    size: "X x X"
    medium: "Lorem Ipsum"
    description: "etc. etc. etc."

**Comment by webmasterkai** [comment]
That would be fine. Really, we just need a little consistency.

**Comment by bjornmeansbear** [comment]
:) It is amazing how people interpreted the instructions.

**Comment by emmasf** [comment]
So, what's next? Does someone (me / Nour / Grad Studies) need to go through and create YAML files for each doc? Is this a save-as task, or is this about making the info standardized?

**Comment by webmasterkai** [comment]
I haven't actually opened the documents to see what format they are in. If they are mostly the same it will be mostly about save-as. Otherwise a combination of the two?

**Comment by bjornmeansbear** [comment]
@emmasf @nourtabet do you guys have time tomorrow to help me go through these docs? if we split up the folders we should be able to get it done pretty quickly.

@webmasterkai you and I need to touch base on the format, but you're saying as long as they are all the same and in .txt it should be fine?

**Comment by webmasterkai** [comment]
All the same in a text file. Much less work for me if they can be in yaml format.

**Comment by emmasf** [comment]
Sure, I can take a third. Just let me know which programs.

Do you want to make a template (sample file) so we know how to set them up? And I don't know how to make a yaml file; if it's easy just let me know how, and if not I can save them as .txt and perhaps you can convert.

**Comment by nourtabet** [comment]
I can't work on this today
I have 5 hours to get to new haven tomorrow that I can work in and update the files once I get online there 

///nour's
///phone

**Comment by bjornmeansbear** [comment]
@emmasf, @nourtabet : 

When @webmasterkai pulled all the images in, they are just in a folder with the students ID# and then only named with 01, 02, 03, etc.

So, in the caption file we'll do this for each section of info:

(no spaces) -
(two spaces) 01:
(four spaces) title: blah
etc.

I did an example one already, CommunityArts-MFA > id0377874 > 377874-imagelist.yml
it doesn't have to be a .yml as long as it is truly plaintext (.txt). So use texteditor in plaintext more, Coda, or Dreamweaver to make sure what you're writing is truly in plaintext.

**Comment by bjornmeansbear** [comment]
I'll do CommunityArts-MFA, Curatorial-MFA, and FineArt-PBacc

**Comment by emmasf** [comment]
To better split up the big ones, I'll do GDMFA, GD PBacc, Hoffberger,
Rinehart

Nour that leaves you Illustration, Mt Royal, PEM, SocialDesign.

Cool?

On Sat, Mar 1, 2014 at 11:47 AM, Kristian Bjørnard <notifications@github.com

**Comment by bjornmeansbear** [comment]
@webmasterkai these are coming along... for sure CommunityArts-MFA, Curatorial-MFA, FineArt-PBacc, and Rinehart-MFA are done... can you try those to make sure they'll work? the rest can then be finished …

**Comment by emmasf** [comment]
sorry, must do tomorrow. :[

On Sat, Mar 1, 2014 at 11:10 PM, Kristian Bjørnard <notifications@github.com

**Comment by emmasf** [comment]
@bjornmeansbear you did Rinehart, yeah? I'm tackling GDMFA, GDPBacc and Hoffberger now.

**Comment by emmasf** [comment]
To confirm: the file name is now 666666-imagelist right?

**Comment by bjornmeansbear** [comment]
Yes, i did rinehart too

**Comment by bjornmeansbear** [comment]
Exactly. You can check mine if you need more confirmation for correctness

**Comment by emmasf** [comment]
Done with my share. Thanks for taking Rinehart.

**Comment by bjornmeansbear** [comment]
Bam! these are getting pulled in... they look rough, so we need to do some styling love, but they are there.

**Comment by emmasf** [comment]
... a lot are missing. All of GDMFA except Nour, for example. Any thoughts?

**Comment by nourtabet** [comment]
AND… the N/A is showing up. hah! should we go in and delete those?

**Comment by bjornmeansbear** [comment]
Ugh... I think I just was omitting the "size" field when they said N/A … I
don't have a good recommendation right now, by brain is a little fried.

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear
