### ISSUE TITLE
standardize gallery names

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#31]
Riggs/Leidy and Riggs and Leidy should display as "Studio Center Galleries"

Anything with Meyerhoff should say "Meyerhoff Gallery"

**Comment by tlupfer** [comment]
@bjornmeansbear So Riggs, Leidy, and Riggs/Leidy should all match the same filter? We have data of all of those types

**Comment by bjornmeansbear** [comment]
Yes those three should all be the same filter -- and they want it to say "Studio Center Galleries" (at least that was the call as of last night)

**Comment by tlupfer** [comment]
Filter has been corrected and I changed the menu items. The only thing left to do is for someone to standarize the actual data (some entries have "Meyerhoff" and some have "Meyerhoff Gallery"), but I'll leave that part to the spreadsheet crew.

**Comment by bjornmeansbear** [comment]
@emmasf @nourtabet I am 90% positive that this is where we pulled in the in gallery names from. 
https://docs.google.com/spreadsheet/ccc?key=0AvPe_NdeKbxjdFFWU0lpSmJYV3NUSlIzcGU1cWRWTnc&usp=drive_web#gid=0
Can you make sure they are the way they are supposed to print out to the website here? that's the easiest place to fix them and have them propagate through the site correctly.

**Comment by bjornmeansbear** [comment]
In the JSON I think the field is called "exhibitionlocation" — @webmasterkai do you remember where this gets pulled in from so we can properly edit the original to reflect some changes?

**Comment by bjornmeansbear** [comment]
@webmasterkai I have updated the sheets that this would potentially pull from. This is ready to be updated!

**Comment by webmasterkai** [comment]
Ok thanks. 30 min and I'll pull them down.

**Comment by emmasf** [comment]
I'm not sure this belongs here, but: Decker has the same issue as Meyerhoff (Sometimes "Decker," sometimes "Decker Gallery").

Also, will you let @nourtabet and I know where this text comes from so we can edit them if need be?

**Comment by bjornmeansbear** [comment]
@emmasf Yeah, I thought I changed all of these, I'll have to figure out where else we might be pulling them in from.

**Comment by bjornmeansbear** [comment]
@emmasf good catch. I found the errant ones still hanging around... next data pull this should be fixed...

**Comment by bjornmeansbear** [comment]
@emmasf Tim and I changed Riggs, Leidy, and Riggs/Leidy to just be "Studio Center Galleries" in the menu, but should they remain semi-spelled out for each person, or should they all just read "Studio Center Galleries" under people's thumbnails?

**Comment by emmasf** [comment]
"Studio Center Galleries" is great for all contexts. Thanks.

**Comment by emmasf** [comment]
.... but while you're at it, we should name them all "Gallery." Things I see that are not that:

D Center
Fox 3

Man, I've never appreciated project managers like I am now.

**Comment by bjornmeansbear** [comment]
@emmasf, @tlupfer — Well, I made all those changes to the google doc they come from... which means the next "pull" will break the gallery sorts, but this will finally be resolved.

**Comment by tlupfer** [comment]
They should be fine if all that you did was append "Gallery"

**Comment by bjornmeansbear** [comment]
yeah, gallery was just added — but the Riggs/Leidy ones were all switched
to just "Studio Center Galleries" since not everyone is listed as being in
one or the other...

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear

**Comment by tlupfer** [comment]
I updated the filters to search for Studio Center Galleries. It appears the json has not been updated just yet, so it's not returning any results.

**Comment by bjornmeansbear** [comment]
yeah, not updated yet, but as soon as it is, bam!
Thanks!

**Comment by bjornmeansbear** [comment]
Marking this closed. When JSON is updated next it will show correctly.
