### ISSUE TITLE
Opening dates/times are wrong

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#33]
Mar 28–Apr 06, 2014
Opening: March 28, 5–8pm

Apr 11–Apr 20, 2014
Opening: April 11, 5–8pm

Apr 23–May 04, 2014
Opening: May 2, 5–8pm

Apr 25–May 04, 2014
Opening: May 2, 5–8pm

**Comment by webmasterkai** [comment]
Is the source for this the spreadsheet or the file in the repo?

**Comment by tlupfer** [comment]
So corrections need to be made to the Schedule and the filter? The filter is currently a JS solution.

**Comment by emmasf** [comment]
Just tried to make an update but got a conflict. Will try again.

The issue is the opening times, not the duration (ie, not start date / end date). I believe the only place we show this data is in the schedule, and it's hard-coded.

**Comment by emmasf** [comment]
.... I fixed this.
