### ISSUE TITLE
Stuff we don't need in the JSON

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#36]
For sure we don't need these things in the JSON data feed:
- pleaseselectyourdesiredtemplatelayoutforthecatalogue
- shortstatementupto75words
- cataloglongstatementupto500words

Is this kind of info useful?

**Comment by webmasterkai** [comment]
That's great. Thanks.

**Comment by bjornmeansbear** [comment]
There is also a "name" entry, this can be left out of the JSON too.

We'll then just need to make sure and only use {{firstname}} {{lastname}} everywhere in the site moustache tag wise, not the {{name}} to make sure that all names are consistent throughout

**Comment by bjornmeansbear** [comment]
we don't appear to need "_d415a": "11/29/2013 15:26:31",
either

**Comment by bjornmeansbear** [comment]
we can also leave out: "suffixegjr."

**Comment by bjornmeansbear** [comment]
and the field: "username":
