### ISSUE TITLE
Left-align single image in overlay

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#39]
Single image looks misaligned since there are no arrows, it looks odd. Just left-align it so it lines up with the text.

**Comment by bjornmeansbear** [comment]
do you truly prefer a) to b)?
![a -nocentering](https://f.cloud.github.com/assets/324987/2303618/2d045e92-a1d4-11e3-8c93-60f6f3244e5e.png)
![b -imgcentering](https://f.cloud.github.com/assets/324987/2303619/2d04cc9c-a1d4-11e3-963f-d284a4ff39ad.png)

**Comment by bjornmeansbear** [comment]
@emmasf — under inspector, find the #slideshow, #singleimg declaration and uncheck the "text-align: center;" to toggle the images left/center to really decide what you prefer. I prefer them centered. But I'll do whatever you two desire.

**Comment by emmasf** [comment]
@nour, you decide. This one looks better centered, but the one I saw earlier (~4x3 horizonal format) was juuuuuust misaligned so it looked bad.

**Comment by bjornmeansbear** [comment]
I'll say it again, I prefer them centered. I did tweak the styling so that in skinny view finders it more or less just fills the area with the image to make this problem less bad.

**Comment by emmasf** [comment]
Okay, you win.

Typed on a phone, please excuse brevity.

**Comment by bjornmeansbear** [comment]
okay, centered it is.
