### ISSUE TITLE
Make sure student ID is always 6 numerical digits and doesn't start ID0

### ISSUE THREAD

**Issue by webmasterkai** [bjornmeansbear/MFAthesis2014#4]

**Comment by bjornmeansbear** [comment]
Where did you specifically notice this as an issue? The images it appears — but elsewhere?
And since there are many hundreds of images, is it okay to change the lesser amount (only about 150) of just digit entries to ID0+ instead? The point is just that they match exactly correct?

**Comment by webmasterkai** [comment]
We can account for it in the code. I think this was as much a note to self as anything.

**Comment by bjornmeansbear** [comment]
I believe this is solved
