### ISSUE TITLE
Weird stuff going on in the spreadsheet...

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#40]
It looks like some of the websites are wrong; they're not typos, they are someone else's url. Not ALL of them are wrong, though, so it's not just that it's gotten shifted in some way. In fact, at least one is a duplicate of one that is correct below. See Ben Chemelski (511543) and Amy Lee Walton (501317).

I'm not sure what the issue is. Thought I'd flag it in case there's an easy solution.

**Comment by bjornmeansbear** [comment]
This is unrelated to the site itself. We only pull stuff in, we don't send data back to google. Something must have gotten mucked up when we've been making edits over the last few days... damn. Further proof that no plan is fool proof :)
