### ISSUE TITLE
Go through spreadsheet for our errors

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#44]

**Comment by emmasf** [comment]
These IDs had someone else's url. I just removed them. We could contact them and ask if they had a url... or we could wait for them to contact us...
539526
516332
516549
338502
406911
518673
520444
518556
491326
481375
536570
377874
512167
539352
512878
539606
528038
491328
424748
540707
420845

**Comment by bjornmeansbear** [comment]
@emmasf This is a data problem not a codebase or development problem. You guys have to decide what to do with this — perhaps just make it Erin and Morgan's problem to solve?

**Comment by emmasf** [comment]
Yep.

Do you guys not want me to capture non dev problems here? I thought it was better to have everything on one place.

**Comment by bjornmeansbear** [comment]
I just didn't want to have the decision re: this assigned to kai, tim or I... if you and nour want to use this venue for things you need resolved as well, that's fine.

**Comment by emmasf** [comment]
Okay, cool. We'll be sure to assign things to ourselves.

**Comment by bjornmeansbear** [comment]
@emmasf @nourtabet did this stuff get resolved? Do you need help going through any of this stuff so we can wrap this up?

**Comment by emmasf** [comment]
We can call this particular issue resolved. Errors are still trickling in, of course, but we decided to let people come to us. These errors are in the spreadsheet below; feel free (and encouraged) to fix anything you see!

https://docs.google.com/a/mica.edu/spreadsheet/ccc?key=0AvPe_NdeKbxjdG9aVXhuREFHMmlTLWFQeG9fdXpLZlE&usp=sharing

**Comment by bjornmeansbear** [comment]
So we'll take stuff from that sheet and fix issues in the live-data sheet? People claiming their images aren't right probably means their ID#s some how got mixed up or misstyped.

**Comment by emmasf** [comment]
Exactly.

I _believe_ Erin and Morgan at Grad Studies are following up with the
people who have image, statement and caption complaints, but they have been
awfully silent...

On Tue, Mar 11, 2014 at 3:36 PM, Kristian Bjørnard <notifications@github.com

**Comment by nourtabet** [comment]
i've been emailing people but didn't go through all the list.
give me a couple of days ill go through everything.
then once it's all done: LET'S PULL DATA one last time
thanks!!
