### ISSUE TITLE
Go through spreadsheet for website url consistency

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#45]
no http://
yes www.

**Comment by emmasf** [comment]
@bjornmeansbear is it worth doing this?

**Comment by bjornmeansbear** [comment]
no http:// is the only thing that is necessary, the www. doesn't matter

**Comment by bjornmeansbear** [comment]
@emmasf there were only a few that had http:// in front of them, so it seemed worth fixing to make sure that everyone's websites would actually load.

**Comment by emmasf** [comment]
ok, will do.
