### ISSUE TITLE
Single Images missing

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#47]
@tlupfer All the stuff we were mucking around in today seems to have broken the single image display, its not finding the images. Let @webmasterkai know if it isn't a template/JS problem and is more likely a data problem — Also, I tried to put the caption data into the display for the single images, will this work when images can be found again?

**Comment by tlupfer** [comment]
Single images are now working. I'll take a look at the caption stuff

**Comment by tlupfer** [comment]
The info is all in the DOM for the caption. Probably an error in the hover. Is that a js thing or css?

**Comment by tlupfer** [comment]
This one is fixed for both captions and images
