### ISSUE TITLE
captions pulling from .txt files aren't working

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#48]

**Comment by webmasterkai** [comment]
That is correct. Some students had both .txt and .yml or .yaml so @bjornmeansbear and I decided we should just use the .yml version. We can add the .txt option again but the students with a file of each must have one removed.

**Comment by emmasf** [comment]
I used .txt when I went through yesterday. @bjornmeansbear said this was fine since I didn't know how to create a yaml file. I'll do whatever's easier, but I would hate to go through all the files again....

**Comment by webmasterkai** [comment]
Can you delete the .txt version out of id0363572? I'll post a few more that have doubles. I think that will be easier than changing the extension.

**Comment by emmasf** [comment]
Sure thing. I'll go though 'em all and delete any extras. Thank you :)

**Comment by emmasf** [comment]
Just to confirm: .doc, .docx, .pages etc are fine, it's just the extra .txt files that have to go?

**Comment by webmasterkai** [comment]
id0363572 might be the only one...

**Comment by emmasf** [comment]
I blew away all the extras... I think there were 3. Thank you!

**Comment by webmasterkai** [comment]
495100, 532322 included?

**Comment by emmasf** [comment]
Yessir.

**Comment by emmasf** [comment]
...I searched for all .txt files in the dropbox folder, deleted any that
weren't what I made yesterday.

**Comment by webmasterkai** [comment]
I think we're good. You should see those on the live site now.

**Comment by bjornmeansbear** [comment]
This appears to be solved.
