### ISSUE TITLE
updating photos: how to 

### ISSUE THREAD

**Issue by nourtabet** [bjornmeansbear/MFAthesis2014#49]
id0532322: his photos were TIFFs and not showing up.
just converted them to jpgs

is there a way for us to update the photos instead of bugging you guys every time?

**Comment by bjornmeansbear** [comment]
@webmasterkai and I are trying to figure that out...

**Comment by webmasterkai** [comment]
I'm working on setting up auto updates that will look for dropbox changes every few minutes.

**Comment by bjornmeansbear** [comment]
@webmasterkai you are my hero.

**Comment by bjornmeansbear** [comment]
@webmasterkai Nour's captions (http://mfa.cape.io/#id=479025) still aren't updated, is the auto-update looking for updated .yml files too? I know there was some problem with hers due to a quote or something that I fixed.

**Comment by webmasterkai** [comment]
yaml should be updated automatically like photos. What's the full path to the file?

**Comment by bjornmeansbear** [comment]
GradShow2014GPAs/GraphicDesign-MFA/id0479025/479025-imagelist.yml
