### ISSUE TITLE
Would be easier having gallery data in a yaml

### ISSUE THREAD

**Issue by webmasterkai** [bjornmeansbear/MFAthesis2014#5]
It's also fine leaving it in the spreadsheet, it just will need to be handled a little differently. https://docs.google.com/a/sundaysenergy.com/spreadsheet/ccc?key=0Al-kEdVYvxtGdDNBZHFWZjB1YnVFX19CSWpHLWczb1E&usp=drive_web#gid=0

**Comment by bjornmeansbear** [comment]
I'll make this.

**Comment by bjornmeansbear** [comment]
This is so.
https://github.com/bjornmeansbear/MFAthesis2014/blob/master/content/galleries.yml
