### ISSUE TITLE
Change "filtered by" text

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#53]
Talking about the text that appears above the student list when a filter is applied. Please change: 

Showdate: > Show Date:

From gallery dropdown:
Gallery: D Center Gallery > Gallery: D Center
Gallery: Decker Gallery > Gallery: Decker
Gallery: Fox 3 Gallery > Gallery: Fox 3 
Gallery: Meyerhoff Gallery > Gallery: Meyerhoff
Gallery: Pinkard Gallery > Gallery: Pinkard

From Map links:
Gallery: Pinkard,Bunting >  Gallery: Pinkard
Gallery: Fox 3,Decker,Meyerhoff > Gallery: Fox 3, Decker, Meyerhoff

(Grad Studies +)

**Comment by tlupfer** [comment]
This one should be done. Please verify it's the way that you want it and close.

**Comment by bjornmeansbear** [comment]
@emmasf can you confirm this is correct... I think its what was asked for too, but just make sure.

**Comment by emmasf** [comment]
Hmm... I didn't see it. I went in and changed in html myself, with the exception on Showdate, which I couldn't find.

**Comment by emmasf** [comment]
Oh, I lied. That's done too. Awesome.!
