### ISSUE TITLE
Change "All Projects" in nav to "All Students"

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#54]

**Comment by bjornmeansbear** [comment]
Well... it seems like #55 makes this obsolete — maybe just remove this from the nav?

**Comment by emmasf** [comment]
I think it's good to have an explicit clear, actually... it's not obvious to me that clicking the main Students nav will clear.  #55 seems like overkill to me honestly but Grad studies wants it, so fine.

**Comment by bjornmeansbear** [comment]
Okay, well than this can just get changed in the HTML. Its just text that
has JS function added separately.

**Comment by tlupfer** [comment]
Done.
