### ISSUE TITLE
When clicking "Students" in nav, clear all filters

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#55]

**Comment by emmasf** [comment]
Grad Studies request. Only if it is easy, I said it might not be.

**Comment by bjornmeansbear** [comment]
@tlupfer — Can this just have the same functionality as "all projects" to satisfice this request?

**Comment by tlupfer** [comment]
This one is completed.

**Comment by bjornmeansbear** [comment]
Thanks @tlupfer
