### ISSUE TITLE
Student statements in overlay should parse html

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#57]
... if that's how you say it.

Either that, or we need to go through and remove a ton of <i></i? and such. I'd prefer to include the styles students want, but if it's a huge pain we can edit out the stylings instead.

**Comment by emmasf** [comment]
@bjornmeansbear @webmasterkai @tlupfer Which route shall we take? People are complaining about their unformatted text so we ought to do one or the other. It would be better to just read the html so people can italicize their titles and such, but if this is difficult we can edit statements.

**Comment by bjornmeansbear** [comment]
the simplest solution is to remove the formatting.
We're stuck on some other things still though and haven't gotten back to
any of this yet.

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear

**Comment by webmasterkai** [comment]
There is html in the statements? Is it just getting escaped now and we want it to display on the site? We can just use three curly braces instead of two and that will leave the html alone...

**Comment by bjornmeansbear** [comment]
yeah, I think there are some <i></i>s for sure, otherwise there might just
be some line breaks or something...

±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

Kristian Bjørnard
Designer / Thinker / Sustainabilitist

ph:  507.301.8402
em: kristian.bjornard@gmail.com
w:   kristian.bjornard.com
w:   thesustainabilitist.com
twitter: @bjornmeansbear

**Comment by emmasf** [comment]
Yes, people included italics and line breaks and such.

Typed on a phone, please excuse brevity.

**Comment by nourtabet** [comment]
@webmasterkai so… should we keep the tags in the statements or delete them?
what's the final verdict on that?

**Comment by nourtabet** [comment]
@bjornmeansbear @webmasterkai @tlupfer :

@emmasf and i finished all the corrections: edited photos in dropbox, edited captions, edited galleries and edited statements/names/url's in the main spreadsheet. 

This issue is the only one pending! woot.

**Comment by bjornmeansbear** [comment]
<i> and the like show up now.

Lines breaks still don't appear to be recognized, but at least we don't have to go in and delete tags...

**Comment by emmasf** [comment]
Works for me. Huzzah.

On Thu, Mar 13, 2014 at 5:11 PM, Kristian Bjørnard <notifications@github.com
