### ISSUE TITLE
pulled data didn't update everyone's files

### ISSUE THREAD

**Issue by nourtabet** [bjornmeansbear/MFAthesis2014#58]
There were students who's data (captions and/or images) weren't updated.
(so far)
Seo Kim 336406
Vincent Purcell 532322
Nour Tabet 479025

(I have edited those folders along others that appear updated, not sure why the update didn't apply to all)

**Comment by bjornmeansbear** [comment]
I Will investigate.

**Comment by webmasterkai** [comment]
I need to pull down the latest from dropbox too. I didn't do that. I thought everything was in the sheets. I can do that later tonight.

**Comment by bjornmeansbear** [comment]
@nourtabet can you confirm if this is done? Is the data up to date for You, Vincent, and Seo?

**Comment by nourtabet** [comment]
@bjornmeansbear @webmasterkai 
can we hold off pulling data from everything till end of this week?
we will need to refresh everything: all photos, captions and spreadsheets.

Some photos have changed for other people as well.

**Comment by bjornmeansbear** [comment]
Vincent appears to be now up to date... 
Is there anyway to confirm if Seo Kim 336406 is up to date @nourtabet or @emmasf 
Also, @nourtabet I will get your captions up there... we're getting close...

**Comment by bjornmeansbear** [comment]
Okay... this should now be done too! hurray.
