### ISSUE TITLE
Remove N/A from captions

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#59]
@tlupfer and @webmasterkai is there an easy way to do this programmatically? Basically, we just need to hide the caption data (e.g. "medium: N/A," not the whole caption) when the input is N/A.

If it's not easy, we'll go through and manually delete them. I just like to ask first because sometimes there's a simple fix that doesn't involve tedious data correction. 

Thank you.

**Comment by webmasterkai** [comment]
@tlupfer this might be a little easier for you to do since you are already accessing the info from the strange object/array/object thing. If not let me know. https://github.com/bjornmeansbear/MFAthesis2014/blob/master/index.html#L547-L555

**Comment by tlupfer** [comment]
sure thing.

**Comment by tlupfer** [comment]
[Problem user's data sanitized](http://mfa.cape.io/#id=479025)

Changes are up on mfa.cape.io.

**Comment by bjornmeansbear** [comment]
This is so. @tlupfer actually fixed a whole bunch of things, missing years, mediums, sizes, you name it all cleaned up. Bam!

**Comment by emmasf** [comment]
I'd buy you a beer if I were in your state, sir.

Typed on a phone, please excuse brevity.

**Comment by tlupfer** [comment]
I sometimes travel for beer.

The only situation that is unaccounted for, is no year, no medium, but a size. In this case, there would be an undesired leading comma. I can fix this if anyone thinks it will happen.

**Comment by bjornmeansbear** [comment]
That shouldn't ever be an issue.
Hurray!
