### ISSUE TITLE
Fix Raymond's Statement if we want to

### ISSUE THREAD

**Issue by emmasf** [bjornmeansbear/MFAthesis2014#60]
> Hi Erin,
> I was told by Nour to contact you about text changes on the website.
> The text itself is OK. I have a question about formatting. Can we start a new paragraph between "imagined" and "Raymond"? There's a perspective shift that is confusing right now. Optimally, the text would be formatted like this:
> 
> As a performance artist, I take on the role of the conspiracy theorist--building worlds, leaving behind artifacts, and manufacturing modern myths. Tactical lectures, synthpop music, and various installations contribute to an expanded narrative concerning the merits of paranoia, confusing notions of authenticity, and confronting systems of power.
> 
> The Truth is out there, and it is stranger than we had ever imagined.
> 
> Raymond Weilacher was born and raised in Oklahoma, USA, where he also received a BFA in media from the University of Oklahoma. When he's not traveling internationally to spread news of extraterrestrial incursions into earth politics, he continues his education at the Maryland Institute College of Art. He currently lives in Baltimore, in an abandoned nuclear missile silo hidden from circling drones.
> 
> Thanks,
> Raymond

**Comment by bjornmeansbear** [comment]
Kai figured this out! Bam!
