### ISSUE TITLE
Image problem in Firefox

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#61]
Images aren't following the CSS the same way as they do in chrome/safari/IE

Also, the 1st image in slideshows is often not loading, again only in FF

will try to look into it 3/20/2014

**Comment by bjornmeansbear** [comment]
F you firefox. why can't you process heights like everything else does... Well, I've mostly fixed an issue with the heights of things... but there is still the problem of various images just not displaying in FF... this is general list:
http://graduate.mica.edu/gradshow/2014/#id=508835
http://graduate.mica.edu/gradshow/2014/#id=491326
http://graduate.mica.edu/gradshow/2014/#id=406911
http://graduate.mica.edu/gradshow/2014/#id=528038
http://graduate.mica.edu/gradshow/2014/#id=518556
http://graduate.mica.edu/gradshow/2014/#id=512878
http://graduate.mica.edu/gradshow/2014/#id=536570
http://graduate.mica.edu/gradshow/2014/#id=473846
http://graduate.mica.edu/gradshow/2014/#id=518573
http://graduate.mica.edu/gradshow/2014/#id=378108
http://graduate.mica.edu/gradshow/2014/#id=511617
http://graduate.mica.edu/gradshow/2014/#id=520018
http://graduate.mica.edu/gradshow/2014/#id=534657
http://graduate.mica.edu/gradshow/2014/#id=524897
http://graduate.mica.edu/gradshow/2014/#id=512170
http://graduate.mica.edu/gradshow/2014/#id=518445
http://graduate.mica.edu/gradshow/2014/#id=501226
http://graduate.mica.edu/gradshow/2014/#id=519030
http://graduate.mica.edu/gradshow/2014/#id=518670
http://graduate.mica.edu/gradshow/2014/#id=497693
http://graduate.mica.edu/gradshow/2014/#id=518471
http://graduate.mica.edu/gradshow/2014/#id=473717
http://graduate.mica.edu/gradshow/2014/#id=501187
http://graduate.mica.edu/gradshow/2014/#id=479025
http://graduate.mica.edu/gradshow/2014/#id=512951
http://graduate.mica.edu/gradshow/2014/#id=499524
http://graduate.mica.edu/gradshow/2014/#id=541963
http://graduate.mica.edu/gradshow/2014/#id=518777
http://graduate.mica.edu/gradshow/2014/#id=519364
http://graduate.mica.edu/gradshow/2014/#id=512848
http://graduate.mica.edu/gradshow/2014/#id=512565
http://graduate.mica.edu/gradshow/2014/#id=514534
http://graduate.mica.edu/gradshow/2014/#id=524822
http://graduate.mica.edu/gradshow/2014/#id=536542
http://graduate.mica.edu/gradshow/2014/#id=408939
http://graduate.mica.edu/gradshow/2014/#id=456952
http://graduate.mica.edu/gradshow/2014/#id=495100
http://graduate.mica.edu/gradshow/2014/#id=519188
http://graduate.mica.edu/gradshow/2014/#id=501607
http://graduate.mica.edu/gradshow/2014/#id=529884
http://graduate.mica.edu/gradshow/2014/#id=519593
http://graduate.mica.edu/gradshow/2014/#id=532322
http://graduate.mica.edu/gradshow/2014/#id=500298
http://graduate.mica.edu/gradshow/2014/#id=517799
http://graduate.mica.edu/gradshow/2014/#id=535270
http://graduate.mica.edu/gradshow/2014/#id=520097
http://graduate.mica.edu/gradshow/2014/#id=539255

It's like bloody 1/2 of them... I'll try to investigate it more tomorrow.

**Comment by webmasterkai** [comment]
Isn't there a thing for this? Isotope and grid/box whatever uses it?

**Comment by bjornmeansbear** [comment]
Okay, getting closer... I at least figured out that it is only width images... so it might be something with my centering CSS around lines 958 onward... trying a few things...

**Comment by bjornmeansbear** [comment]
Problem solved.
