### ISSUE TITLE
Order problem in some slideshows

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#62]
There are a few more, but this one for sure: http://graduate.mica.edu/gradshow/2014/#id=491326

The slideshow is starting at 03, and Images 01 and 02 are showing in the 9th and 10th places instead. The captions are ordered correctly, which means the captions and images don't line up...

**Comment by tlupfer** [comment]
Should be corrected at http://mfa.cape.io/#id=491326

**Comment by bjornmeansbear** [comment]
woohoo. as far as I can tell this is now working. I'll update the MICA live version.
