### ISSUE TITLE
Where should additional files for download live?

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/MFAthesis2014#8]
Currently we have a PDF in the "PDF" folder, but it isn't found on the cape.io server

**Comment by webmasterkai** [comment]
Maybe I forgot to include PDF in the list of file ext to copy

**Comment by bjornmeansbear** [comment]
So they don't have to be moved, it just needs to be included. cool

**Comment by bjornmeansbear** [comment]
this is fixed.
